# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8049cda4-3de6-488f-9378-7012b749e051";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/72C5-6AA1";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/98638be3-910c-4ef2-8bfc-a4f65c247f4b";
      fsType = "ext4";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/20ae3687-61a8-45fe-87aa-456d320322ab";
      fsType = "ext4";
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/d08e1fae-4e22-403b-b51b-56e7cb389beb";
      fsType = "ext4";
    };

  #fileSystems."/mnt/cle" = 
  #  { device = "/dev/disk/by-uuid/7A820A337AC4B45D";
  #    fsType = "ntfs";
  #    options = [ "rw" "uid=1000" ];
  #  };

  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-uuid/26B2C6A6B2C679B7";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4825de35-2cc2-4ce8-8290-d960d013d5f6"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
