# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "async-cache-1.0.0" = {
      name = "async-cache";
      packageName = "async-cache";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-cache/-/async-cache-1.0.0.tgz";
        sha1 = "c87f6d80c72b394ee0f9061edeb24d8c4b622ada";
      };
    };
    "bl-1.0.3" = {
      name = "bl";
      packageName = "bl";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.0.3.tgz";
        sha1 = "fc5421a28fd4226036c3b3891a66a25bc64d226e";
      };
    };
    "buffer-writer-1.0.0" = {
      name = "buffer-writer";
      packageName = "buffer-writer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-writer/-/buffer-writer-1.0.0.tgz";
        sha1 = "6c29c3b2dea0c9e455a1f261a199a48a04f88b08";
      };
    };
    "busboy-0.2.14" = {
      name = "busboy";
      packageName = "busboy";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/busboy/-/busboy-0.2.14.tgz";
        sha1 = "6c2a622efcf47c57bbbe1e2a9c37ad36c7925453";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "connect-3.3.5" = {
      name = "connect";
      packageName = "connect";
      version = "3.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-3.3.5.tgz";
        sha1 = "d1d9958c90a830bb429271e7a0a4aaaa9d033cab";
      };
    };
    "connect-route-0.1.5" = {
      name = "connect-route";
      packageName = "connect-route";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect-route/-/connect-route-0.1.5.tgz";
        sha1 = "e3c218319d2e88a8a9ae0b0e0fe09a729c39744a";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "debug-2.1.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.1.3.tgz";
        sha1 = "ce8ab1b5ee8fbee2bfa3b633cab93d366b63418e";
      };
    };
    "dicer-0.2.5" = {
      name = "dicer";
      packageName = "dicer";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dicer/-/dicer-0.2.5.tgz";
        sha1 = "5996c086bb33218c812c090bddc09cd12facb70f";
      };
    };
    "ee-first-1.1.0" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.0.tgz";
        sha1 = "6a0d7c6221e490feefd92ec3f441c9ce8cd097f4";
      };
    };
    "escape-html-1.0.1" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz";
        sha1 = "181a286ead397a39a92857cfb1d43052e356bff0";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fd-0.0.3" = {
      name = "fd";
      packageName = "fd";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd/-/fd-0.0.3.tgz";
        sha512 = "iAHrIslQb3U68OcMSP0kkNWabp7sSN6d2TBSb2JO3gcLJVDd4owr/hKM4SFJovFOUeeXeItjYgouEDTMWiVAnA==";
      };
    };
    "finalhandler-0.3.4" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.4.tgz";
        sha1 = "4787d3573d079ae8b07536f26b0b911ebaf2a2ac";
      };
    };
    "generic-pool-2.1.1" = {
      name = "generic-pool";
      packageName = "generic-pool";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-pool/-/generic-pool-2.1.1.tgz";
        sha1 = "af04dc2c325cfcb975023fa52bfce9617a7435fd";
      };
    };
    "graceful-fs-4.1.15" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.15.tgz";
        sha512 = "6uHUhOPEBgQ24HM+r6b/QwWfZq+yiFcipKFrOFiBEnWdy5sdzYoi+pJeQaPI5qOLRFqWmAXUPQNsielzdLoecA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json5-0.4.0" = {
      name = "json5";
      packageName = "json5";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.4.0.tgz";
        sha1 = "054352e4c4c80c86c0923877d449de176a732c8d";
      };
    };
    "lru-cache-2.3.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.3.1.tgz";
        sha1 = "b3adf6b3d856e954e2c390e6cef22081245a53d6";
      };
    };
    "memcache-0.3.0" = {
      name = "memcache";
      packageName = "memcache";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memcache/-/memcache-0.3.0.tgz";
        sha1 = "bdbb978ea4bee0fdd3166997b1883d297e0859dc";
      };
    };
    "mime-1.3.6" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.6.tgz";
        sha1 = "591d84d3653a6b0b4a3b9df8de5aa8108e72e5e0";
      };
    };
    "ms-0.7.0" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.0.tgz";
        sha1 = "865be94c2e7397ad8a57da6a633a6e2f30798b83";
      };
    };
    "negotiator-0.5.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz";
        sha1 = "269d5c476810ec92edbe7b6c2f28316384f9a7e8";
      };
    };
    "on-finished-2.2.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.2.1.tgz";
        sha1 = "5c85c1cc36299f78029653f667f27b6b99ebc029";
      };
    };
    "packet-reader-0.2.0" = {
      name = "packet-reader";
      packageName = "packet-reader";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/packet-reader/-/packet-reader-0.2.0.tgz";
        sha1 = "819df4d010b82d5ea5671f8a1a3acf039bcd7700";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "pg-4.3.0" = {
      name = "pg";
      packageName = "pg";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg/-/pg-4.3.0.tgz";
        sha1 = "fbeed09363e9258500354fc97d3dd7566ff758fe";
      };
    };
    "pg-connection-string-0.1.3" = {
      name = "pg-connection-string";
      packageName = "pg-connection-string";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-0.1.3.tgz";
        sha1 = "da1847b20940e42ee1492beaf65d49d91b245df7";
      };
    };
    "pg-int8-1.0.1" = {
      name = "pg-int8";
      packageName = "pg-int8";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz";
        sha512 = "WCtabS6t3c8SkpDBUlb1kjOs7l66xsGdKpIPZsg4wR+B3+u9UAum2odSsF9tnvxg80h4ZxLWMy4pRjOsFIqQpw==";
      };
    };
    "pg-types-1.13.0" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-1.13.0.tgz";
        sha512 = "lfKli0Gkl/+za/+b6lzENajczwZHc7D5kiUCZfgm914jipD2kIOIvEkAhZ8GrW3/TUoP9w8FHjwpPObBye5KQQ==";
      };
    };
    "pgpass-0.0.3" = {
      name = "pgpass";
      packageName = "pgpass";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pgpass/-/pgpass-0.0.3.tgz";
        sha1 = "12e67e343b3189c2f31206ebc9cc0befffcf9140";
      };
    };
    "pkginfo-0.3.1" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.1.tgz";
        sha1 = "5b29f6a81f70717142e09e765bbeab97b4f81e21";
      };
    };
    "postgres-array-1.0.3" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-1.0.3.tgz";
        sha512 = "5wClXrAP0+78mcsNX3/ithQ5exKvCyK5lr5NEEEeGwwM6NJdQgzIJBVxLvRW+huFpX92F2QnZ5CcokH0VhK2qQ==";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha1 = "027b533c0aa890e26d172d47cf9ccecc521acd35";
      };
    };
    "postgres-date-1.0.7" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.7.tgz";
        sha512 = "suDmjLVQg78nMK2UZ454hAG+OAW+HQPZ6n++TNDUX+L0+uUlLywnoxJKDou51Zm+zTCjrCl0Nq6J9C5hP9vK/Q==";
      };
    };
    "postgres-interval-1.2.0" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.2.0.tgz";
        sha512 = "9ZhXKM/rw350N1ovuWHbGxnGh/SNJ4cnxHiM0rxE4VN41wsg8P8zWn9hv/buK00RP4WvlOyr/RBDiptyxVbkZQ==";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "redis-0.12.1" = {
      name = "redis";
      packageName = "redis";
      version = "0.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-0.12.1.tgz";
        sha1 = "64df76ad0fc8acebaebd2a0645e8a48fac49185e";
      };
    };
    "redis-url-0.3.1" = {
      name = "redis-url";
      packageName = "redis-url";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-url/-/redis-url-0.3.1.tgz";
        sha1 = "b54dc93bb7517e4fa07d64199d9540eb27795372";
      };
    };
    "semver-4.3.6" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.6.tgz";
        sha1 = "300bc6e0e86374f7ba61068b5b1ecd57fc6532da";
      };
    };
    "split-0.3.3" = {
      name = "split";
      packageName = "split";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-0.3.3.tgz";
        sha1 = "cd0eea5e63a211dfff7eb0f091c4133e2d0dd28f";
      };
    };
    "st-0.5.5" = {
      name = "st";
      packageName = "st";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/st/-/st-0.5.5.tgz";
        sha1 = "c4cefdb08458e9dfc3b5e223705ddbca2514c3b5";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "streamsearch-0.1.2" = {
      name = "streamsearch";
      packageName = "streamsearch";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsearch/-/streamsearch-0.1.2.tgz";
        sha1 = "808b9d0e56fc273d809ba57338e929919a1a9f1a";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "winston-0.9.0" = {
      name = "winston";
      packageName = "winston";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-0.9.0.tgz";
        sha1 = "b5726e6c42291e305e36286ce7ae9f3b74a527a8";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  haste-server = nodeEnv.buildNodePackage {
    name = "haste-server";
    packageName = "haste-server";
    version = "0.2.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/haste-server/-/haste-server-0.2.1.tgz";
      sha1 = "01288025be5a955dab1b956fde617a2e3c2af0a2";
    };
    dependencies = [
      sources."async-0.9.2"
      sources."async-cache-1.0.0"
      (sources."bl-1.0.3" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."readable-stream-2.0.6"
        ];
      })
      sources."buffer-writer-1.0.0"
      sources."busboy-0.2.14"
      sources."colors-1.0.3"
      sources."connect-3.3.5"
      sources."connect-route-0.1.5"
      sources."core-util-is-1.0.3"
      sources."cycle-1.0.3"
      sources."debug-2.1.3"
      sources."dicer-0.2.5"
      sources."ee-first-1.1.0"
      sources."escape-html-1.0.1"
      sources."eyes-0.1.8"
      sources."fd-0.0.3"
      sources."finalhandler-0.3.4"
      sources."generic-pool-2.1.1"
      sources."graceful-fs-4.1.15"
      sources."inherits-2.0.4"
      sources."isarray-0.0.1"
      sources."isstream-0.1.2"
      sources."json5-0.4.0"
      sources."lru-cache-2.3.1"
      sources."memcache-0.3.0"
      sources."mime-1.3.6"
      sources."ms-0.7.0"
      sources."negotiator-0.5.3"
      sources."on-finished-2.2.1"
      sources."packet-reader-0.2.0"
      sources."parseurl-1.3.3"
      sources."pg-4.3.0"
      sources."pg-connection-string-0.1.3"
      sources."pg-int8-1.0.1"
      sources."pg-types-1.13.0"
      sources."pgpass-0.0.3"
      sources."pkginfo-0.3.1"
      sources."postgres-array-1.0.3"
      sources."postgres-bytea-1.0.0"
      sources."postgres-date-1.0.7"
      sources."postgres-interval-1.2.0"
      sources."process-nextick-args-1.0.7"
      sources."readable-stream-1.1.14"
      sources."redis-0.12.1"
      sources."redis-url-0.3.1"
      sources."semver-4.3.6"
      sources."split-0.3.3"
      sources."st-0.5.5"
      sources."stack-trace-0.0.10"
      sources."streamsearch-0.1.2"
      sources."string_decoder-0.10.31"
      sources."through-2.3.8"
      sources."util-deprecate-1.0.2"
      sources."utils-merge-1.0.0"
      sources."winston-0.9.0"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A damn simple and pretty pastebin server.";
      homepage = "https://github.com/jirutka/haste-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
